// Core
const DO_LOGIN_FAIL = "DO_LOGIN_FAIL"
const DO_LOGIN_SUCCESS = "DO_LOGIN_SUCCESS"
const DO_RESET_LOGIN_STATE = "DO_RESET_LOGIN_STATE"

const DO_LOGOUT_FAIL = "DO_LOGOUT_FAIL"
const DO_LOGOUT_SUCCESS = "DO_LOGOUT_SUCCESS"
const DO_RESET_LOGOUT_STATE = "DO_RESET_LOGOUT_STATE"

const DO_SIGNUP_FAIL = "DO_SIGNUP_FAIL"
const DO_SIGNUP_SUCCESS = "DO_SIGNUP_SUCCESS"
const DO_RESET_SIGNUP_STATE = "DO_RESET_SIGNUP_STATE"

const DO_GET_LOGGEDIN_USER_SUCCESS = "DO_GET_LOGGEDIN_USER_SUCCESS"
const DO_GET_LOGGEDIN_USER_FAIL = "DO_GET_LOGGEDIN_USER_FAIL"

const DO_GET_INSURANCES_SUCCESS = "DO_GET_INSURANCES_SUCCESS"
const DO_GET_INSURANCES_FAIL = "DO_GET_INSURANCES_FAIL"

const DO_GET_META_SUCCESS = "DO_GET_META_SUCCESS"
const DO_GET_META_FAIL = "DO_GET_META_FAIL"

const DO_GET_INSURANCE_RATE_SUCCESS = "DO_GET_INSURANCE_RATE_SUCCESS"
const DO_GET_INSURANCE_RATE_FAIL = "DO_GET_INSURANCE_RATE_FAIL"

const DO_GET_SALES_USER_DETAIL_SUCCESS = "DO_GET_SALES_USER_DETAIL_SUCCESS"
const DO_GET_SALES_USER_DETAIL_FAIL = "DO_GET_SALES_USER_DETAIL_FAIL"
const DO_RESET_SALES_STATE = "DO_RESET_SALES_STATE"

const DO_STORE_CUSTOMER_APPLICATION_SUCCESS = "DO_STORE_CUSTOMER_APPLICATION_SUCCESS"
const DO_STORE_CUSTOMER_APPLICATION_FAIL = "DO_STORE_CUSTOMER_APPLICATION_FAIL"

const DO_UPDATE_CUSTOMER_APPLICATION_SUCCESS = "DO_UPDATE_CUSTOMER_APPLICATION_SUCCESS"
const DO_UPDATE_CUSTOMER_APPLICATION_FAIL = "DO_UPDATE_CUSTOMER_APPLICATION_FAIL"

const DO_RESET_STORE_CUSTOMER_APPLICATION = "DO_RESET_STORE_CUSTOMER_APPLICATION"
const DO_RESET_GET_PACAKGE_RATE_STATE = "DO_RESET_GET_PACAKGE_RATE_STATE"

// Forgot Password
const SEND_FORGOT_PASSWORD_SUCCESS = "SEND_FORGOT_PASSWORD_SUCCESS"
const SEND_FORGOT_PASSWORD_FAIL = "SEND_FORGOT_PASSWORD_FAIL"
const SEND_RESET_PASSWORD_SUCCESS = "SEND_RESET_PASSWORD_SUCCESS"
const SEND_RESET_PASSWORD_FAIL = "SEND_RESET_PASSWORD_FAIL"
const RESET_FORGOT_PASSWORD_STATE = "RESET_FORGOT_PASSWORD_STATE"

// Verify Email
const DO_VERIFY_EMAIL_SUCCESS = "DO_VERIFY_EMAIL_SUCCESS"
const DO_VERIFY_EMAIL_FAIL = "DO_VERIFY_EMAIL_FAIL"
const DO_RESET_VERIFY_EMAIL_STATE = "DO_RESET_VERIFY_EMAIL_STATE"

// User Profile
const DO_UPDATE_USER_PROFILE_SUCCESS = "DO_UPDATE_USER_PROFILE_SUCCESS"
const DO_UPDATE_USER_PROFILE_FAIL = "DO_UPDATE_USER_PROFILE_FAIL"
const DO_RESET_USER_PROFILE_STATE = "DO_RESET_USER_PROFILE_STATE"
const DO_CHANGE_PASSWORD_SUCCESS = "DO_CHANGE_PASSWORD_SUCCESS"
const DO_CHANGE_PASSWORD_FAIL = "DO_CHANGE_PASSWORD_FAIL"
const DO_RESET_CHANGE_PASSWORD_STATE = "DO_RESET_CHANGE_PASSWORD_STATE"
const DO_SEND_CURRENT_EMAIL_VERIFICATION_CODE_SUCCESS =
    "DO_SEND_CURRENT_EMAIL_VERIFICATION_CODE_SUCCESS"
const DO_SEND_CURRENT_EMAIL_VERIFICATION_CODE_FAIL = "DO_SEND_CURRENT_EMAIL_VERIFICATION_CODE_FAIL"
const DO_CONFIRM_CURRENT_EMAIL_VERIFICATION_CODE_SUCCESS =
    "DO_CONFIRM_CURRENT_EMAIL_VERIFICATION_CODE_SUCCESS"
const DO_CONFIRM_CURRENT_EMAIL_VERIFICATION_CODE_FAIL =
    "DO_CONFIRM_CURRENT_EMAIL_VERIFICATION_CODE_FAIL"
const DO_SEND_NEW_EMAIL_VERIFICATION_CODE_SUCCESS = "DO_SEND_NEW_EMAIL_VERIFICATION_CODE_SUCCESS"
const DO_SEND_NEW_EMAIL_VERIFICATION_CODE_FAIL = "DO_SEND_NEW_EMAIL_VERIFICATION_CODE_FAIL"
const DO_CONFIRM_NEW_EMAIL_VERIFICATION_CODE_SUCCESS =
    "DO_CONFIRM_NEW_EMAIL_VERIFICATION_CODE_SUCCESS"
const DO_CONFIRM_NEW_EMAIL_VERIFICATION_CODE_FAIL = "DO_CONFIRM_NEW_EMAIL_VERIFICATION_CODE_FAIL"

// MY PURCHASE
const DO_GET_MY_PURCHASE_LIST_SUCCESS = "DO_GET_MY_PURCHASE_LIST_SUCCESS"
const DO_GET_MY_PURCHASE_LIST_FAIL = "DO_GET_MY_PURCHASE_LIST_FAIL"
const DO_GET_MY_PURCHASE_DETAILS_SUCCESS = "DO_GET_MY_PURCHASE_DETAILS_SUCCESS"
const DO_GET_MY_PURCHASE_DETAILS_FAIL = "DO_GET_MY_PURCHASE_DETAILS_FAIL"
const DO_DOWNLOAD_QUOTATION_SUCCESS = "DO_DOWNLOAD_QUOTATION_SUCCESS"
const DO_DOWNLOAD_QUOTATION_FAIL = "DO_DOWNLOAD_QUOTATION_FAIL"
const DO_RESEND_VERIFICATION_EMAIL_SUCCESS = "DO_RESEND_VERIFICATION_EMAIL_SUCCESS"
const DO_RESEND_VERIFICATION_EMAIL_FAIL = "DO_RESEND_VERIFICATION_EMAIL_FAIL"

module.exports = {
    // Core
    DO_LOGIN_FAIL,
    DO_LOGIN_SUCCESS,
    DO_RESET_LOGIN_STATE,

    DO_LOGOUT_FAIL,
    DO_LOGOUT_SUCCESS,
    DO_RESET_LOGOUT_STATE,

    DO_SIGNUP_FAIL,
    DO_SIGNUP_SUCCESS,
    DO_RESET_SIGNUP_STATE,

    DO_GET_LOGGEDIN_USER_SUCCESS,
    DO_GET_LOGGEDIN_USER_FAIL,

    DO_GET_INSURANCES_SUCCESS,
    DO_GET_INSURANCES_FAIL,

    DO_GET_META_SUCCESS,
    DO_GET_META_FAIL,

    DO_GET_INSURANCE_RATE_SUCCESS,
    DO_GET_INSURANCE_RATE_FAIL,

    DO_GET_SALES_USER_DETAIL_SUCCESS,
    DO_GET_SALES_USER_DETAIL_FAIL,
    DO_RESET_SALES_STATE,

    DO_STORE_CUSTOMER_APPLICATION_SUCCESS,
    DO_STORE_CUSTOMER_APPLICATION_FAIL,

    DO_UPDATE_CUSTOMER_APPLICATION_SUCCESS,
    DO_UPDATE_CUSTOMER_APPLICATION_FAIL,

    DO_RESET_STORE_CUSTOMER_APPLICATION,
    DO_RESET_GET_PACAKGE_RATE_STATE,

    // Forgot Password
    SEND_FORGOT_PASSWORD_SUCCESS,
    SEND_FORGOT_PASSWORD_FAIL,
    SEND_RESET_PASSWORD_SUCCESS,
    SEND_RESET_PASSWORD_FAIL,
    RESET_FORGOT_PASSWORD_STATE,

    // Verify Email
    DO_VERIFY_EMAIL_SUCCESS,
    DO_VERIFY_EMAIL_FAIL,
    DO_RESET_VERIFY_EMAIL_STATE,

    // User Profile
    DO_UPDATE_USER_PROFILE_SUCCESS,
    DO_UPDATE_USER_PROFILE_FAIL,
    DO_RESET_USER_PROFILE_STATE,
    DO_CHANGE_PASSWORD_SUCCESS,
    DO_CHANGE_PASSWORD_FAIL,
    DO_RESET_CHANGE_PASSWORD_STATE,
    DO_SEND_CURRENT_EMAIL_VERIFICATION_CODE_SUCCESS,
    DO_SEND_CURRENT_EMAIL_VERIFICATION_CODE_FAIL,
    DO_CONFIRM_CURRENT_EMAIL_VERIFICATION_CODE_SUCCESS,
    DO_CONFIRM_CURRENT_EMAIL_VERIFICATION_CODE_FAIL,
    DO_SEND_NEW_EMAIL_VERIFICATION_CODE_SUCCESS,
    DO_SEND_NEW_EMAIL_VERIFICATION_CODE_FAIL,
    DO_CONFIRM_NEW_EMAIL_VERIFICATION_CODE_SUCCESS,
    DO_CONFIRM_NEW_EMAIL_VERIFICATION_CODE_FAIL,
    DO_RESEND_VERIFICATION_EMAIL_SUCCESS,
    DO_RESEND_VERIFICATION_EMAIL_FAIL,

    // MY PURCHASE
    DO_GET_MY_PURCHASE_LIST_SUCCESS,
    DO_GET_MY_PURCHASE_LIST_FAIL,
    DO_GET_MY_PURCHASE_DETAILS_SUCCESS,
    DO_GET_MY_PURCHASE_DETAILS_FAIL,
    DO_DOWNLOAD_QUOTATION_SUCCESS,
    DO_DOWNLOAD_QUOTATION_FAIL,
}
