// Core
const SIDEBAR_SHOW = "SIDEBAR_SHOW"
const SET_INSURANCE_DETAILS = "SET_INSURANCE_DETAILS"
const SET_SELECTED_INSURANCE = "SET_SELECTED_INSURANCE"
const SET_INSURANCE_RATE_DETAILS = "SET_INSURANCE_RATE_DETAILS"
const SET_INSURANCES = "SET_INSURANCES"
const SET_WATCH_INSURANCE_COVERAGE = "SET_WATCH_INSURANCE_COVERAGE"
const SET_IS_SPOUSE = "SET_IS_SPOUSE"
const SET_ERROR_CODE_CONFIRM_DATA = "SET_ERROR_CODE_CONFIRM_DATA"
const SET_CODE_CONFIRM_SUCCESS = "SET_CODE_CONFIRM_SUCCESS"
const SET_ERROR_NEW_CODE_CONFIRM_DATA = "SET_ERROR_NEW_CODE_CONFIRM_DATA"
const SET_NEW_CODE_CONFIRM_SUCCESS = "SET_NEW_CODE_CONFIRM_SUCCESS"
const SET_NEW_CODE_SENT_SUCCESS = "SET_NEW_CODE_SENT_SUCCESS"
const SET_CODE_SENT_SUCCESS = "SET_CODE_SENT_SUCCESS"
const SET_ERROR_CODE_SENT_DATA = "SET_ERROR_CODE_SENT_DATA"
const SET_RESEND_EMAIL_VERIFICATION = "SET_RESEND_EMAIL_VERIFICATION"

module.exports = {
    SIDEBAR_SHOW,
    SET_INSURANCE_DETAILS,
    SET_SELECTED_INSURANCE,
    SET_INSURANCE_RATE_DETAILS,
    SET_INSURANCES,
    SET_WATCH_INSURANCE_COVERAGE,
    SET_IS_SPOUSE,
    SET_ERROR_CODE_CONFIRM_DATA,
    SET_CODE_CONFIRM_SUCCESS,
    SET_ERROR_NEW_CODE_CONFIRM_DATA,
    SET_NEW_CODE_CONFIRM_SUCCESS,
    SET_NEW_CODE_SENT_SUCCESS,
    SET_CODE_SENT_SUCCESS,
    SET_ERROR_CODE_SENT_DATA,
    SET_RESEND_EMAIL_VERIFICATION,
}
